create table if not exists public.respostas_enare_pernambuco (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  apelido text not null constraint respostas_enare_pernambuco_apelido_length check (char_length(btrim(apelido)) between 3 and 24),
  nota numeric not null constraint respostas_enare_pernambuco_nota_range check (nota between 0 and 100),
  ano_nascimento integer not null constraint respostas_enare_pernambuco_ano_nascimento_range check (ano_nascimento between 1930 and 2010),
  modalidade text not null constraint respostas_enare_pernambuco_modalidade_valid check (modalidade in ('AC', 'PNP')),
  programa_id integer not null constraint respostas_enare_pernambuco_programa_id_positive check (programa_id >= 1),
  prioridade integer not null constraint respostas_enare_pernambuco_prioridade_range check (prioridade between 1 and 3)
);

create index if not exists respostas_enare_pernambuco_ranking_idx
  on public.respostas_enare_pernambuco (nota desc, ano_nascimento asc);

create index if not exists respostas_enare_pernambuco_filtros_idx
  on public.respostas_enare_pernambuco (programa_id, modalidade);

alter table public.respostas_enare_pernambuco enable row level security;

drop policy if exists "service_role_full_access_respostas_enare_pernambuco" on public.respostas_enare_pernambuco;
create policy "service_role_full_access_respostas_enare_pernambuco"
  on public.respostas_enare_pernambuco
  as permissive
  for all
  to service_role
  using (true)
  with check (true);

comment on table public.respostas_enare_pernambuco is 'Respostas colaborativas do ranking ENARE Pernambuco — Psicologia.';
